version: "3.8"
services:

  postgres:
    image: postgres:14
    container_name: postgres-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vpnbot
    ports:
      - "5432:5432"
