spring:
  application:
    name: coffee-vpn
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    properties.hibernate.show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #open-in-view: false

logging:
  level:
    root: info

server:
  port: 8090
  servlet:
    contextPath: /coffee
