spring:
  datasource:
    url: jdbc:postgresql://103.136.41.156:5432/vpnbot
    username: root
    password: root

config:
  cli:
    key-gen-command: wg genkey | tee /Users/ilyaguzenko/Desktop/bot-test-folder/{0}/{0}_privatekey | wg pubkey | tee /Users/ilyaguzenko/Desktop/bot-test-folder/{0}/{0}_publickey
    work-dir: /Users/ilyaguzenko/Desktop/bot-test-folder
  file:
    dns: 8.8.8.8
    public-key: iSAk7NSZQTub+ZI4z53cK2dNhXZyEhaiESWLC6WYnVU=
    endpoint: 103.136.41.156:51830
    allowed-ips: 0.0.0.0/0
    persistent-keepalive: 20
  bot:
    name: coffee_vpn_test_bot
    token: 5761121762:AAEGLLGi8py8zpmVJnZiqfxJqpolIhARcFY
